name: Playwright Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Install dependencies
      working-directory: automation
      run: npm install


    - name: Install Playwright browsers
      working-directory: automation
      run: npx playwright install


    - name: Start application
      working-directory: app
      run: |
        npm install
        node server.js &


    - name: Run Playwright tests
      working-directory: automation
      run: npx playwright test